#folder where the fastq files are
fastq_files: /Users/annaleigh/Documents/data/4su_bams/fastq/
#lazy way of pulling out all the sample names in the fastq fiels
#eventual output folder for the whippet analysis
data_output_path: /SAN/vyplab/alb_projects/data/muscle/analysis/whippets/
#full path to your julia install
julia_path = "/Applications/Julia-0.6.app/Contents/Resources/julia/bin/julia"
#the path for the whippset-quant jl script
whippet_bin = "/home/annbrown/alb_projects/tools/julia_pkgdir/v0.6/Whippet/bin/"
#the path where your samtools is installed
samtools_path = "/share/apps/genomics/samtools-1.9/bin/samtools"
#the path to the julia index (we're going to make a rule later to define this)
INDEX = "/Users/annaleigh/.julia/v0.6/Whippet/index/with_merged_bams.jls"
#first rule of a snakemake file always defines the final desired output. Eventually this file should produced the psi file
#and the sorted bam 