__default__:
    h_vmem: 2G
    h_rt:   1:0:0
majiq_build:
    h_vmem:   8G
    tmem:   8G
    pe: smp 2
    h_rt: 72:00:00
    R:  y
majiq_psi:
    h_vmem:   2G
    tmem:   2G
    pe: smp 2
    h_rt: 72:00:00
    R:  y
majiq_psi_tsv:
    h_vmem:   1G
    tmem:   1G
    pe: smp 2
    h_rt: 72:00:00
    R:  y
majiq_delta_psi_tsv:
    h_vmem:   1G
    tmem:   1G
    h_rt: 72:00:00
build_whippet_index:
    h_vmem:   6G
    tmem:   6G
    h_rt: 72:00:00
