
# ########IBM GEO information
species: mouse
library_type: fr-secondstrand
read_len: 75
genome_refcode: mm10
strand_code: none
endtype: se
sample_csv_path: /home/annbrown/data/linked_bams_agaribotag/sample_listing.csv
group_column: group
######TOP LEVEL PROJECT FOLDER
top_level_project_folder: /SAN/vyplab/alb_projects/data/linked_bams_agaribotag/
whippet_output_path: whippets/
whippet_index_name: gencode.v34
#directory of all the already aligned bam files, this is necessary for building the majic data index from this data
bam_dir: /home/annbrown/data/linked_bams_agaribotag/bams/
run_name: agaRiboSplice
#folder where the fastq files are

majiq_top_level: /home/annbrown/data/linked_bams_agaribotag/bams/majiq/

majiq_extra_parameters:
  simplify:
majiq_psi_extra_parameters:
extra_voila_parameters:
  threshold: "0.1"

fasta: /SAN/vyplab/vyplab_reference_genomes/sequence/mouse/gencode/GRCm38.primary_assembly.genome.fa
gtf: /SAN/vyplab/vyplab_reference_genomes/annotation/mouse/gencode/gencode.vM22.annotation.gtf
gff3: /SAN/vyplab/vyplab_reference_genomes/annotation/mouse/gencode/gencode.vM22.annotation.gff3

# fasta: /SAN/vyplab/vyplab_reference_genomes/sequence/human/gencode/GRCh38.primary_assembly.genome.fa
# gtf: /SAN/vyplab/vyplab_reference_genomes/annotation/human/GRCh38/gencode.v31.annotation.gtf
# gff3: /SAN/vyplab/vyplab_reference_genomes/annotation/human/GRCh38/gencode.v31.annotation.gff3




#scallop configurations
scallop_path: /SAN/vyplab/alb_projects/tools/scallop-0.10.4/src/scallop
scallop_extra_parameters:
  library_type: first
  min_transcript_length_increase: 25



###### Whippets configurations
whippet_indicies: /SAN/vyplab/vyplab_reference_genomes/whippets_index/
whippet_extra_parameters:
  bam-min-reads: 10
# -------------------------- Global configurations which shouldn't need to be
# -------------------------- adjusted.

julia: /SAN/vyplab/alb_projects/tools/julia-9d11f62bcb/bin/julia
bam_suffix: .pass2Aligned.sortedByCoord.out
#the path where your samtools is installed
samtools_path: /share/apps/genomics/samtools-1.9/bin/samtools
cufflinks_path: /share/apps/genomics/cufflinks-2.2.1/bin/cufflinks
majiq_path: /SAN/vyplab/alb_projects/tools/majiq_env/bin/python3 /SAN/vyplab/alb_projects/tools/majiq_env/bin/majiq
voila_path: /SAN/vyplab/alb_projects/tools/majiq_env/bin/python3 /SAN/vyplab/alb_projects/tools/majiq_env/bin/voila
# return of the whippets, whippets strikes back
whippet_bin: /SAN/vyplab/alb_projects/tools/julia_pkgdir/v0.6/Whippet/bin/
