
# ########IBM GEO information
species: human
library_type: fr-secondstrand
read_len: 76
genome_refcode: hg38
strand_code: forward
endtype: pe
sample_csv_path: /home/annbrown/data/ward_bams/ward_bams.csv
group_column: group

#directory of all the already aligned bam files, this is necessary for building the majic data index from this data
bam_dir: /home/annbrown/data/ward_bams/bam_files/
run_name: wardTDPKD
#folder where the fastq files are
fastq_files: /SAN/vyplab/alb_projects/data/combined_muscle_ibm_bams_linked/merged_fastqs/
majiq_top_level: /SAN/vyplab/alb_projects/data/ward_bams/majiq/

majiq_extra_parameters:
  simplify:
majiq_psi_extra_parameters:
extra_voila_parameters:
  threshold: "0.1"

# fasta: /SAN/vyplab/vyplab_reference_genomes/sequence/mouse/gencode/GRCm38.primary_assembly.genome.fa
# gtf: /SAN/vyplab/vyplab_reference_genomes/annotation/mouse/gencode/gencode.vM22.annotation.gtf
# gff3: /SAN/vyplab/vyplab_reference_genomes/annotation/mouse/gencode/gencode.vM22.annotation.gff3

fasta: /SAN/vyplab/vyplab_reference_genomes/sequence/human/gencode/GRCh38.primary_assembly.genome.fa
gtf: /SAN/vyplab/vyplab_reference_genomes/annotation/human/GRCh38/gencode.v31.annotation.gtf
gff3: /SAN/vyplab/vyplab_reference_genomes/annotation/human/GRCh38/gencode.v31.annotation.gff3



# Whippets configurations

whippet_output_path: /SAN/vyplab/alb_projects/data/muscle/analysis/whippets/
whippet_extra_parameters:
  suppress-low-tsl:
  bam-min-reads: 10
# -------------------------- Global configurations which shouldn't need to be
# -------------------------- adjusted.


julia: /SAN/vyplab/alb_projects/tools/julia-9d11f62bcb/bin/julia
bam_suffix: .pass2Aligned.sortedByCoord.out
#the path where your samtools is installed
samtools_path: /share/apps/genomics/samtools-1.9/bin/samtools
cufflinks_path: /share/apps/genomics/cufflinks-2.2.1/bin/cufflinks
majiq_path: /SAN/vyplab/alb_projects/tools/majiq_env/bin/python3 /SAN/vyplab/alb_projects/tools/majiq_env/bin/majiq
voila_path: /SAN/vyplab/alb_projects/tools/majiq_env/bin/python3 /SAN/vyplab/alb_projects/tools/majiq_env/bin/voila
# return of the whippets, whippets strikes back
whippet_bin: /SAN/vyplab/alb_projects/tools/julia_pkgdir/v0.6/Whippet/bin/
