
sampleCSVpath: /SAN/vyplab/alb_projects/data/muscle/wide_fastq.csv
majiq_config: /SAN/vyplab/alb_projects/data/muscle/analysis/majiq/majiqConfig.tsv
#folder where the fastq files are
fastq_files: /Users/annaleigh/Documents/data/4su_bams/fastq/
#lazy way of pulling out all the sample names in the fastq fiels
#eventual output folder for the whippet analysis
#directory of all the already aligned bam files, this is necessary for building the whippets data index from this data
bam_dir: /SAN/vyplab/alb_projects/data/muscle/analysis/STAR_aligned/
data_output_path: /SAN/vyplab/alb_projects/data/muscle/analysis/whippets/
run_name: muscle
#full path to your julia install
julia: /SAN/vyplab/alb_projects/tools/julia-9d11f62bcb/bin/julia
#the path for the whippset-quant jl script
whippet_bin: /SAN/vyplab/alb_projects/tools/julia_pkgdir/v0.6/Whippet/bin/
#the path where your samtools is installed
samtools_path: /share/apps/genomics/samtools-1.9/bin/samtools
majiq_path: /share/apps/python-3.6.9/bin/majiq

fasta: /SAN/vyplab/vyplab_reference_genomes/sequence/human/GRCh38/Homo_sapiens.GRCh38.dna.primary_assembly.fa
gtf: /SAN/vyplab/vyplab_reference_genomes/annotation/human/GRCh38/Homo_sapiens.GRCh38.96.gtf
gff3: /SAN/vyplab/vyplab_reference_genomes/annotation/human/GRCh38/ref_GRCh38.p12_top_level.gff3.gz

majiq_builder_output: /SAN/vyplab/alb_projects/data/muscle/analysis/majiq/builder
