
# ########IBM GEO information
species: human
library_type: fr-firststrand
read_len: 150
genome_refcode: hg38
strand_code: none
endtype: pe
sample_csv_path: /SAN/vyplab/alb_projects/data/muscle/wide_fastq.csv
group_column: group

majiq_top_level: /SAN/vyplab/alb_projects/data/muscle/analysis/majiq_disable_denovo/

#directory of all the already aligned bam files, this is necessary for building the majic data index from this data
bam_dir: /SAN/vyplab/alb_projects/data/muscle/analysis/STAR_aligned/
run_name: disable_denovo
#folder where the fastq files are

majiq_extra_parameters:
  simplify:
  disable-denovo:
extra_voila_parameters:
  threshold: "0.1"

fasta: /SAN/vyplab/vyplab_reference_genomes/sequence/human/GRCh38/Homo_sapiens.GRCh38.dna.primary_assembly.fa
gtf: /SAN/vyplab/vyplab_reference_genomes/annotation/human/GRCh38/gencode.v31.annotation.gtf
gff3: /SAN/vyplab/vyplab_reference_genomes/annotation/human/GRCh38/gencode.v31.annotation.gff3




# -------------------------- Global configurations which shouldn't need to be
# -------------------------- adjusted.



bam_suffix: .Aligned.sorted.out
#the path where your samtools is installed
samtools_path: /share/apps/genomics/samtools-1.9/bin/samtools
cufflinks_path: /share/apps/genomics/cufflinks-2.2.1/bin/cufflinks
majiq_path: /SAN/vyplab/alb_projects/tools/majiq_env/bin/python3 /SAN/vyplab/alb_projects/tools/majiq_env/bin/majiq
voila_path: /SAN/vyplab/alb_projects/tools/majiq_env/bin/python3 /SAN/vyplab/alb_projects/tools/majiq_env/bin/voila
# return of the whippets, whippets strikes back
whippet_bin: /SAN/vyplab/alb_projects/tools/julia_pkgdir/v0.6/Whippet/bin/
